import { defineConfig } from 'tsup';

export default defineConfig([
  {
    name: 'main',
    format: ['cjs', 'esm'],
    entry: ['./src/index.ts'],
    treeshake: true,
    sourcemap: true,
    minify: true,
    clean: true,
    dts: true,
    external: [
      '@bgd-labs/react-web3-icons',
      '@heroicons/react',
      '@radix-ui/react-dialog',
      '@radix-ui/react-select',
      '@tuwaio/orbit-core',
      '@tuwaio/orbit-evm',
      '@tuwaio/orbit-solana',
      '@tuwaio/satellite-core',
      '@tuwaio/satellite-evm',
      '@tuwaio/satellite-react',
      '@tuwaio/satellite-solana',
      '@tuwaio/pulsar-core',
      '@tuwaio/nova-core',
      '@tuwaio/nova-transactions',
      '@wallet-standard/app',
      '@wallet-standard/base',
      '@wallet-standard/features',
      '@wallet-standard/core',
      '@wallet-standard/ui',
      '@wallet-standard/ui-registry',
      '@wagmi/core',
      '@wagmi/connectors',
      'gill',
      'dayjs',
      'immer',
      'ethereum-blockies-base64',
      'framer-motion',
      '@emotion/is-prop-valid',
      'react',
      'react-toastify',
      'viem',
      'zustand',
    ],
  },
  {
    name: 'hooks',
    format: ['cjs', 'esm'],
    entry: ['./src/hooks/index.ts'],
    outDir: 'dist/hooks',
    treeshake: true,
    sourcemap: true,
    minify: true,
    clean: true,
    dts: true,
    external: [
      '@bgd-labs/react-web3-icons',
      '@heroicons/react',
      '@radix-ui/react-dialog',
      '@radix-ui/react-select',
      '@tuwaio/orbit-core',
      '@tuwaio/orbit-evm',
      '@tuwaio/orbit-solana',
      '@tuwaio/satellite-core',
      '@tuwaio/satellite-evm',
      '@tuwaio/satellite-react',
      '@tuwaio/satellite-solana',
      '@tuwaio/pulsar-core',
      '@tuwaio/nova-core',
      '@tuwaio/nova-transactions',
      '@wallet-standard/app',
      '@wallet-standard/base',
      '@wallet-standard/features',
      '@wallet-standard/core',
      '@wallet-standard/ui',
      '@wallet-standard/ui-registry',
      '@wagmi/core',
      '@wagmi/connectors',
      'gill',
      'dayjs',
      'immer',
      'ethereum-blockies-base64',
      'framer-motion',
      '@emotion/is-prop-valid',
      'react',
      'react-toastify',
      'viem',
      'zustand',
    ],
  },
  {
    name: 'providers',
    format: ['cjs', 'esm'],
    entry: ['./src/providers/index.ts'],
    outDir: 'dist/providers',
    treeshake: true,
    sourcemap: true,
    minify: true,
    clean: true,
    dts: true,
    external: [
      '@bgd-labs/react-web3-icons',
      '@heroicons/react',
      '@radix-ui/react-dialog',
      '@radix-ui/react-select',
      '@tuwaio/orbit-core',
      '@tuwaio/orbit-evm',
      '@tuwaio/orbit-solana',
      '@tuwaio/satellite-core',
      '@tuwaio/satellite-evm',
      '@tuwaio/satellite-react',
      '@tuwaio/satellite-solana',
      '@tuwaio/pulsar-core',
      '@tuwaio/nova-core',
      '@tuwaio/nova-transactions',
      '@wallet-standard/app',
      '@wallet-standard/base',
      '@wallet-standard/features',
      '@wallet-standard/core',
      '@wallet-standard/ui',
      '@wallet-standard/ui-registry',
      '@wagmi/core',
      '@wagmi/connectors',
      'gill',
      'dayjs',
      'immer',
      'ethereum-blockies-base64',
      'framer-motion',
      '@emotion/is-prop-valid',
      'react',
      'react-toastify',
      'viem',
      'zustand',
    ],
  },
  {
    name: 'evm',
    format: ['cjs', 'esm'],
    entry: ['./src/evm/index.ts'],
    outDir: 'dist/evm',
    treeshake: true,
    sourcemap: true,
    minify: true,
    clean: true,
    dts: true,
    external: [
      '@bgd-labs/react-web3-icons',
      '@heroicons/react',
      '@radix-ui/react-dialog',
      '@radix-ui/react-select',
      '@tuwaio/orbit-core',
      '@tuwaio/orbit-evm',
      '@tuwaio/orbit-solana',
      '@tuwaio/satellite-core',
      '@tuwaio/satellite-evm',
      '@tuwaio/satellite-react',
      '@tuwaio/satellite-solana',
      '@tuwaio/pulsar-core',
      '@tuwaio/nova-core',
      '@tuwaio/nova-transactions',
      '@wallet-standard/app',
      '@wallet-standard/base',
      '@wallet-standard/features',
      '@wallet-standard/core',
      '@wallet-standard/ui',
      '@wallet-standard/ui-registry',
      '@wagmi/core',
      '@wagmi/connectors',
      'gill',
      'dayjs',
      'immer',
      'ethereum-blockies-base64',
      'framer-motion',
      '@emotion/is-prop-valid',
      'react',
      'react-toastify',
      'viem',
      'zustand',
    ],
  },
  {
    name: 'solana',
    format: ['cjs', 'esm'],
    entry: ['./src/solana/index.ts'],
    outDir: 'dist/solana',
    treeshake: true,
    sourcemap: true,
    minify: true,
    clean: true,
    dts: true,
    external: [
      '@bgd-labs/react-web3-icons',
      '@heroicons/react',
      '@radix-ui/react-dialog',
      '@radix-ui/react-select',
      '@tuwaio/orbit-core',
      '@tuwaio/orbit-evm',
      '@tuwaio/orbit-solana',
      '@tuwaio/satellite-core',
      '@tuwaio/satellite-evm',
      '@tuwaio/satellite-react',
      '@tuwaio/satellite-solana',
      '@tuwaio/pulsar-core',
      '@tuwaio/nova-core',
      '@tuwaio/nova-transactions',
      '@wallet-standard/app',
      '@wallet-standard/base',
      '@wallet-standard/features',
      '@wallet-standard/core',
      '@wallet-standard/ui',
      '@wallet-standard/ui-registry',
      '@wagmi/core',
      '@wagmi/connectors',
      'gill',
      'dayjs',
      'immer',
      'ethereum-blockies-base64',
      'framer-motion',
      '@emotion/is-prop-valid',
      'react',
      'react-toastify',
      'viem',
      'zustand',
    ],
  },
]);
