import { defineConfig } from 'tsup';

export default defineConfig([
  {
    name: 'main',
    format: ['cjs', 'esm'],
    entry: ['./src/index.ts'],
    treeshake: true,
    sourcemap: true,
    minify: true,
    clean: true,
    dts: true,
    external: [
      '@tuwaio/orbit-core',
      '@tuwaio/orbit-evm',
      '@tuwaio/orbit-solana',
      '@tuwaio/satellite-core',
      '@tuwaio/satellite-evm',
      '@tuwaio/satellite-solana',
      '@wagmi/core',
      '@wagmi/connectors',
      'viem',
      '@wallet-standard/react',
      'gill',
      'react',
      'immer',
      'zustand',
    ],
  },
  {
    name: 'evm',
    format: ['cjs', 'esm'],
    entry: ['./src/evm/index.ts'],
    outDir: 'dist/evm',
    treeshake: true,
    sourcemap: true,
    minify: true,
    clean: true,
    dts: true,
    external: [
      '@tuwaio/orbit-core',
      '@tuwaio/orbit-evm',
      '@tuwaio/orbit-solana',
      '@tuwaio/satellite-core',
      '@tuwaio/satellite-evm',
      '@tuwaio/satellite-solana',
      '@wagmi/core',
      '@wagmi/connectors',
      'viem',
      '@wallet-standard/react',
      'gill',
      'react',
      'immer',
      'zustand',
    ],
  },
  {
    name: 'solana',
    format: ['cjs', 'esm'],
    entry: ['./src/solana/index.ts'],
    outDir: 'dist/solana',
    treeshake: true,
    sourcemap: true,
    minify: true,
    clean: true,
    dts: true,
    external: [
      '@tuwaio/orbit-core',
      '@tuwaio/orbit-evm',
      '@tuwaio/orbit-solana',
      '@tuwaio/satellite-core',
      '@tuwaio/satellite-evm',
      '@tuwaio/satellite-solana',
      '@wagmi/core',
      '@wallet-standard/react',
      'gill',
      'react',
      'immer',
      'zustand',
    ],
  },
]);
